---
stages:
- build
- release
- canary

###################################################
build:
  stage: build
  image: gradle:7.3.1-jdk17  # Use Gradle with JDK 17 to build the app
  artifacts:
    paths:
      # Pass the JAR file to the next stage to include it in the Docker image
      - build/libs/backendify-0.0.1-SNAPSHOT.jar
  script:
    # Clean and build the Gradle project, excluding tests
    - gradle clean build -x test
###################################################

###################################################
## do not remove or edit this block, it is
## required for us to accept your submission!
release:
  stage: release
  image: docker:stable
  services:
  - docker:dind
  before_script:
  - until docker version ; do sleep 1; done
  - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
  - docker build --pull -t ${CI_REGISTRY_IMAGE} .
  - docker push ${CI_REGISTRY_IMAGE}

canary:
  stage: canary
  image: registry.gitlab.com/autoiterativesolutions/src/monolith/ais-client:master
  script: [ "/usr/bin/ais-client" ]
##
###################################################
